### ISSUE TITLE
[MC v1.10.2] Crash when adding DynmapBlockScan 

### ISSUE THREAD

**Issue by xemnes** [webbukkit/DynmapBlockScan#15]
using version DynmapBlockScan-3.0-alpha-1-forge-1.10.2 dated 22-Oct-2017

notable mods that generates any blocks:
conquest reforged
wallpapercraft
chisels and bits
extra bits manipulation

crash log: https://pastebin.com/50W5nPwT

**Comment by drrugg** [comment]
+1 crashes in 1.10 (Foolcraft2 and as noted below), have previously had it working worked fine in 1.12 (for a 1.12 ATM3 server).

**Reproduction**

1.10 with Forge (12.18.3 or .2) with any one mod - crashes with attached error: https://pastebin.com/2nzDwm67 - looks like the scan kicks in after spawn area loads, successfully parses core blocks, then after a couple of blocks hits a null pointer. Tested with BoP and AstralSorcery in particular (cut down from Foolcraft2 pack during testing).

Same instance without additional mods will load world correctly after spawn loading.

Just for note - reusing the 1.12 generated files work great in 1.10 instances (for AE2 RFTools Elevators etc), just not these two. I imagine there isn't a place for people to share working .txt files to easy the burden on you?

**Comment by generrosity** [comment]
I found that the Jan-2018 version of this has helped now.

**Comment by mikeprimm** [comment]
Cool - I think this was a dup of another problem that was fixed recently.  Let me know if you see other issues, and just open additional tickets here.

**Comment by xemnes** [comment]
i tried the newer version from january 2018 (from here http://mikeprimm.com/dynmap/builds/DynmapBlockScan/ ) and it still crashes with the same error https://pastebin.com/AzBbXy1x

**Comment by xemnes** [comment]
you deleted the entire lot? including your config?

**Comment by generrosity** [comment]
Initial yes, via folder rename. Then copied key files over. I keep a list of the changes I've made, which are only a few, so I don't mind re doing some of it

**Comment by xemnes** [comment]
tried your method, it didnt solve the problem unfortunately :/

**Comment by generrosity** [comment]
Yea nah - sorry, thats why I regenerated it from scratch to prove what was going on, and using 'HEAD' (v3?) for both dynmap and dynmapblockscan. I don't know how 2.4 reacts with it - I think I recall you need to match versions?

**Comment by mikeprimm** [comment]
DynmapBlockScan and Dynmap v3.0 are pretty matched at this point - definitely update both together, at least until I get to a release level someday.  Any correct function with the v2.5 alpha or earlier builds is coincidental, at best.

**Comment by xemnes** [comment]
yup, updating dynmap fixed it, thanks!

**Comment by generrosity** [comment]
Woop! Glad that got sorted.
